server:
  port: 13000

spring:
  profiles:
    include: sharding

  redis:
    host: 192.168.200.130
    password: Lfy123!@!
    lettuce:
      pool:
        max-active: 16
        min-idle: 0


app:
  props:
    ware-url: http://localhost:14000

#feign:
#  client:
#    config:
#      ware-manage:
#        re