server:
  port: 80
#配置公共东西


#配置请求转发规则
#断言
spring:
  redis:
    host: 192.168.200.130
    password: Lfy123!@!
#    lettuce:
#      pool:  #响应式编程中不要配置普通的池
#        max-active: 16
#        min-idle: 0

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"  #允许所有ip跨域访问
            allowedMethods: "*"  #允许所有请求方式
            allowedHeaders: "*"  #允许任何头进行跨域
            allowCredentials: true #允许携带cookie
            ## 以上配完成，简单跨域复杂跨域都允许。

      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

        - id: lb_test
          uri: lb://service-item
          predicates:
            - Path=/redis/incr

        - id: user_route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        - id: web_all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com,gmall.com


app:
  auth:
    anyoneurls:  #所有人无需登录就能访问的url
      - /js/**
      - /css/**
      - /img/**
      - /static/**
    denyurls:  #任何情况下都拒绝访问。
      - /rpc/inner/**
    authurls: #必须登录才能访问的请求
      - /order.html
    loginPage: http://passport.gmall.com/login.html