server:
  port: 8000
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true


  rabbitmq:
    host: 192.168.200.130
    port: 5672
    username: admin
    password: admin
    virtualHost: /
    publisher-returns: true
    #发送端确认；
    publisher-confirm-type: correlated
    #手动ack机制
    listener:
      type: simple
      simple:
        acknowledge-mode: manual  #手动确认模式。









